name: together
description: An app for friends to play games remotely.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  material_design_icons_flutter:

  cloud_functions: ^0.4.2+2
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_database: ^3.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/together_icon.png

flutter:
  uses-material-design: true
  fonts:
    - family: Balsamiq
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Italic.ttf
          style: italic
