name: together
description: An app for friends to play games remotely.

version: 1.1.10+22

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  material_design_icons_flutter:
  transformer_page_view: 
  shimmer: ^1.1.1
  auto_size_text: ^2.1.0
  marquee_widget: ^0.8.0
  audioplayers: ^0.15.0

  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  # firebase_crashlytics: ^0.1.3+3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/together_icon.png

flutter:
  uses-material-design: true
  fonts:
    - family: Balsamiq
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Italic.ttf
          style: italic
  assets:
    - assets/sounds/approved-notification.wav
    - assets/sounds/birds.mp3
    - assets/sounds/complete-notification.wav
    - assets/sounds/excellent.wav
    - assets/sounds/giant-breathing.wav
    - assets/sounds/howling.wav
    - assets/sounds/music-box-1.wav
    - assets/sounds/music-box-2.mp3
    - assets/sounds/music-box-3.mp3
    - assets/sounds/new-lobby.mp3
    - assets/sounds/new-player.wav
    - assets/sounds/open-notification.mp3
    - assets/sounds/reveal.wav
    - assets/sounds/sent-notification.wav

 