name: together
description: For friends to play games.

version: 1.4.0+42

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  provider:
  material_design_icons_flutter:
  transformer_page_view: 
  shimmer:
  auto_size_text:
  marquee_widget:
  # audioplayers: ^0.16.1
  random_words:
  simple_animations:
  string_similarity:
  speech_to_text:
  rxdart:
  clipboard:
  flushbar:

  firebase_core:
  firebase_analytics:
  # firebase_crashlytics: ^0.1.3+3
  firebase_auth:
  cloud_firestore:
  firebase_storage:

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

  # speech_to_text:
  #   path: ../speech_to_text/speech_to_text/

flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/together_icon.png

flutter:
  uses-material-design: true
  fonts:
    - family: Balsamiq
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Italic.ttf
          style: italic
    - family: SyneMono
      fonts:
        - asset: assets/fonts/SyneMono-Regular.ttf
  assets:
    - assets/images/matt_aki.jpg
    - assets/sounds/approved-notification.wav
    - assets/sounds/birds.mp3
    - assets/sounds/complete-notification.wav
    - assets/sounds/excellent.wav
    - assets/sounds/giant-breathing.wav
    - assets/sounds/howling.wav
    - assets/sounds/music-box-1.wav
    - assets/sounds/music-box-2.mp3
    - assets/sounds/music-box-3.mp3
    - assets/sounds/new-lobby.mp3
    - assets/sounds/new-player.wav
    - assets/sounds/open-notification.mp3
    - assets/sounds/reveal.wav
    - assets/sounds/sent-notification.wav

 