name: together
description: For friends to play games.

version: 1.5.2+51

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  material_design_icons_flutter: ^4.0.5855
  transformer_page_view: ^0.1.6
  shimmer: ^1.1.2
  auto_size_text: ^2.1.0
  marquee_widget: ^1.0.0
  random_words: ^1.0.2
  simple_animations: ^2.5.1
  string_similarity: ^1.1.0
  speech_to_text: ^3.1.0
  rxdart: ^0.25.0
  clipboard: ^0.1.2+8
  flushbar:
  url_launcher: ^5.7.10
  # audioplayers: ^0.16.1

  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.4.0+1
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0

dev_dependencies:
  flutter_launcher_icons:
    git:
      url: https://github.com/knyghtryda/flutter_launcher_icons
      ref: scaling
  # flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/together_icon.png
  adaptive_icon_background: "#a7e6ff"
  adaptive_icon_foreground: "assets/icon/together_icon.png"
  adaptive_icon_foreground_scale_factor: 0.66

flutter:
  uses-material-design: true
  fonts:
    - family: Balsamiq
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Italic.ttf
          style: italic
    - family: SyneMono
      fonts:
        - asset: assets/fonts/SyneMono-Regular.ttf
  assets:
    - assets/images/matt_aki.jpg
    - assets/sounds/approved-notification.wav
    - assets/sounds/birds.mp3
    - assets/sounds/complete-notification.wav
    - assets/sounds/excellent.wav
    - assets/sounds/giant-breathing.wav
    - assets/sounds/howling.wav
    - assets/sounds/music-box-1.wav
    - assets/sounds/music-box-2.mp3
    - assets/sounds/music-box-3.mp3
    - assets/sounds/new-lobby.mp3
    - assets/sounds/new-player.wav
    - assets/sounds/open-notification.mp3
    - assets/sounds/reveal.wav
    - assets/sounds/sent-notification.wav

 