List<String> bananaphonePossiblePrompts = [
  'dolphin',
  'nightmare',
  'iPhone',
  'Oregon',
  'calendar',
  'music',
  'succulent',
  'keyboard',
  'trombone',
  'cigarette',
  'pie',
  'police',
  'bread',
  'chair',
  'supermarket',
  'airplane',
  'university',
  'Italy',
  'Greece',
  'yard',
  'storm',
  'manager',
  'throat',
  'finger',
  'camp',
  'conversation',
  'eat',
  'fuel',
  'man',
  'woman',
  'detail',
  'desk',
  'nail',
  'world',
  'tree',
  'village',
  'exercise',
  'mess',
  'floor',
  'tongue',
  'birthday',
  'ball',
  'airplane',
  'animal',
  'battle',
  'take-off',
  'frame',
  'farm',
  'balcony',
  'horizon',
  'money',
  'half',
  'bell',
  'glove',
  'internet',
  'SUV',
  'wood',
  'corner',
  'magazine',
  'gun',
  'ice',
  'shoe',
  'bottom',
  'book',
  'summer',
  'father',
  'gene',
  'kiss',
  'strategy',
  'towel',
  'vacation',
  'emergency',
  'guard',
  'sunset',
  'coffee',
  'egg',
  'joke',
  'gate',
  'beer',
  'ticket',
  'mountain',
  'sort',
  'chemical',
  'metal',
  'week',
  'snow',
  'belt',
  'key',
  'switch',
  'map',
  'sail',
  'skirt',
  'curve',
  'shine',
  'queen',
  'ear',
  'angle',
  'fruit',
  'tennis',
  'author',
  'closet',
  'collar',
  'tourist',
  'devil',
  'friend',
  'signature',
  'hotel',
  'copy',
  'hair',
  'chain',
  'sand',
  'burger',
  'aquarium',
  'cat',
  'game',
  'DJ',
  'jet-ski',
  'home run',
  'roof',
];

List<String> bananaphonePossiblePromptsHard = [
  'Skiing with Barack Obama',
  'Giving a monkey a unicorn',
  'Sleeping all night in a fridge',
  'Officiating a porcupine wedding',
  'A balloon turning into a sandwich',
  'Singing upside down in a pool',
  'On the highway to heaven',
  'Punching ten bicycles',
  'Denying entry to a caveman',
  'A hippo sliding down a pyramid',
  'Golfing with a keyboard',
  'Two grains of rice',
  'An alligator walking into a blackhole',
  'A poisonous llama',
  'Mario doing the splits',
  'Japan and Europe',
  'A wooden helicopter',
  'Jumping into a giant bowl of cereal',
  'Moon dancing on the moon',
  'Pushing eight buttons at the same time',
  'Screaming at a telephone',
  'Becoming friends with a radish',
  'Ziplining with Beyonce',
  'Surfing in a kitchen sink',
  'A potato with four legs',
  'Throwing a scooter into a shopping cart',
  'Painting the Mona Lisa',
  'Helping a dragon sneeze',
  'Invading Florida',
  'Touching the corner of a Rubik\'s cube',
  'Drinking champagne with a shark',
  'Throwing a touchdown with a soccer ball',
  'Cooling your feet with some palm leaves',
  'Whipping the Titanic with a whip',
  'Installing a dating app on your phone',
  'City-wide blackout',
  'Smashing an alarm clock',
  'Abraham Lincoln mowing the lawn',
  'The solar system exploding',
  'A zebra hula-hooping',
  'Shaving a mullet off',
  'Apple walking in a park',
  'Horse made of candy',
  'Pinocchio paragliding',
  'Neighbors being noisy',
  'Sticking your foot in the fridge',
  'An elephant in camouflage',
  'A man with twelve fingers and eight toes',
  'Scuba-diving in lava',
  'Worms having lunch',
  'A pineapple machinegun',
  'Two trees bowing to each other',
  'Two skyscrapers hugging',
  'Juggling books',
  'A cute doctor',
  'A salivating buffalo',
  'Climbing the side of a library',
  'Pulling the moon to Earth',
  'An exploding baseball',
  'Coffin full of Jello',
  'Eating colors',
  'Walking on your elbows',
  'A pig-shaped kite',
  'A beach without sand',
  'Slapping someone with a steak',
  'Turtle flying in the air',
  'Cutting fruit with a spoon',
  'A fox hiding in a tophat',
  'Dumping trash on the lawn',
  'Playing the piano on a plane',
  'A bear starting a fire',
  'A vampire clapping',
  'A rock concert with no crowd',
  'A couple bananas in the road',
  'A fast sloth',
  'Too much makeup',
  'A lizard with tiny legs',
  'Boujee ants',
  'Riding a slide to the center of the Earth',
  'Rubbing avocado on your face',
  'Cereal without milk',
  'A sky-diving clown',
  'Sitting on a trashcan',
  
];

List<String> abstractPossibleWords = [
  'apple',
  'cider',
  'chocolate',
  'cream',
  'snap',
  'mountain',
  'swamp',
  'chess',
  'universe',
  'galaxy',
  'moon',
  'cart',
  'list',
  'smash',
  'jump',
  'blink',
  'red',
  'blue',
  'human',
  'whale',
  'turtle',
  'cat',
  'warp',
  'machine',
  'pencil',
  'eye',
  'nail',
  'hammer',
  'igloo',
  'desert',
  'cloud',
  'rain',
  'lake',
  'party',
  'dance',
  'football',
  'basketball',
  'castle',
  'Hogwarts',
  'blackboard',
  'nostril',
  'uniform',
  'hammock',
  'stencil',
  'mistake',
  'distance',
  'fog',
  'London',
  'Japan',
  'Russia',
  'Venezuela',
  'rodeo',
  'Texas',
  'frosting',
  'cake',
  'vape pen',
  'terrorist',
  'Mt Everest',
  'ocean',
  'China',
  'Brad Pitt',
  'microscope',
  'best',
  'nonsense',
  'green',
  'mammoth',
  'shrimp',
  '\'90s',
  'wave',
  'location',
  'walkie-talkie',
  'wall',
  'Europe',
  'orc',
  'elf',
  'forest',
  'destroy',
  'balloon',
  'caveman',
  'railing',
  'wallpaper',
  'mousepad',
  'contact',
  'reciprocate',
  'deny',
  'laugh',
  'Santa',
  'screen',
  'check',
  'clock',
  'water',
  'well',
  'volcano',
  'coffee',
  'dinosaur',
  'harbor',
  'labor',
  'Jesus',
  'keyboard',
  'incinerator',
  'prime minister',
  'button',
  'LED',
  'owl',
  'cheetah',
  'giraffe',
  'university',
  'shame',
  'blush',
  'flower',
  'movie',
  'reconcile',
  'brush',
  'decide',
  'spot',
  'ring',
  'platypus',
  'bird',
  'deny',
  'worship',
  'charcoal',
  'smash',
  'livid',
  'orange',
  'minus',
  'divide',
  'register',
  'plank',
  'Mongolia',
  'Egypt',
  'pyramid',
  'infinity',
  'repeat',
  'rewind',
  'save',
  'cup',
  'wag',
  'Marilyn Monroe',
  'Abraham Lincoln',
  'Taylor Swift',
  'Elvis Presley',
  'Oprah Winfrey',
  'Tiger Woods',
  'David Beckham',
  'George Clooney',
  'Tom Hanks',
  'Superman',
  'Adolph Hitler',
  'Leonardo DaVinci',
  'Skrillex',
  'Justin Bieber',
  'Barack Obama',
  'Cristiano Ronaldo',
  'Bruce Willis',
  'Frank Sinatra',
  'Nelson Mandela',
  'Albert Einstein',
  'Vincent Van Gogh',
  'Thomas Edison',
  'Nicola Tesla',
  'J.K. Rowling',
  'John Lennon',
  'Cleopatra',
  'Usain Bolt',
  'Anne Frank',
  'Tom Cruise',
  'nurse',
  'space',
  'rabbit',
  'eager',
  'blade',
  'coat',
  'snow',
  'lawyer',
  'cute',
  'coal',
  'power',
  'alarm',
  'fair',
  'tire',
  'grab',
  'tail',
  'egg',
  'child',
  'meal',
  'pour',
  'bread',
  'fuzzy',
  'tooth',
  'soar',
  'Google',
  'Facebook',
  'team',
  'passenger',
  'summon',
  'kiss',
  'spy',
  'curve',
  'glove',
  'generation',
  'husk',
  'Italy',
  'Greece',
  'Jessica Alba',
  'Skype',
  'control',
  'diminish',
  'reset',
  'grade',
  'lemur',
  'yellow',
  'gold',
  'Britain',
  'Alaska',
  'Hawaii',
  'swing',
  'sweat',
  'sweater',
  'pull',
  'yoyo',
  'Sudoku',
  'acceptable',
  'ruin',
  'sponge',
  'wisdom',
  'cremation',
  'Aztec',
  'dolphin',
  'account',
  'wire',
  'unearth',
  'spit',
  'wind',
  'build',
  'icicle',
  'lightning',
  'thunder',
  'beggar',
  'attend',
  'require',
];
