
  List<String> abstractPossibleWords = [
    'apple',
    'cider',
    'chocolate',
    'cream',
    'snap',
    'mountain',
    'swamp',
    'chess',
    'universe',
    'galaxy',
    'moon',
    'cart',
    'list',
    'smash',
    'jump',
    'blink',
    'red',
    'blue',
    'human',
    'whale',
    'turtle',
    'cat',
    'warp',
    'machine',
    'pencil',
    'eye',
    'nail',
    'hammer',
    'igloo',
    'desert',
    'cloud',
    'rain',
    'lake',
    'party',
    'dance',
    'football',
    'basketball',
    'castle',
    'Hogwarts',
    'blackboard',
    'nostril',
    'uniform',
    'hammock',
    'stencil',
    'mistake',
    'distance',
    'fog',
    'London',
    'Japan',
    'Russia',
    'Venezuela',
    'Skrillex',
    'Justin Bieber',
    'Barack Obama',
    'rodeo',
    'Texas',
    'frosting',
    'cake',
    'vape pen',
    'terrorist',
    'Mt Everest',
    'ocean'
    'China',
    'Brad Pitt',
    'microscope',
    'best',
    'nonsense',
    'green',
  ];